### ISSUE TITLE
Add meson.build, travis and circle ci

### ISSUE THREAD

**Issue by jmh530** [libmir/mir-stat#2]

**Comment by jmh530** [comment]
@9il I started looking at the `meson.build` file in `mir-algorithm` and have adapted it to below. I wasn't sure how exactly to handle the dependency on mir-algorithm here. You use a subproject for mir-core in that one. Do the same here (but for mir-algorithm)? If not, then what to put?

```
project('mir-stat', 'd', version : '0.0.0', license: 'BSL-1.0')

description = 'Dlang Statistical Package'

sources_list = [
    'mir/stat/descriptive',
    'mir/stat/package',
    'mir/stat/transform',
]

sources = []
foreach s : sources_list
    sources += 'source/' + s + '.d'
endforeach

add_project_arguments([
    '-preview=dip1008',
    '-lowmem',
], language: 'd')

required_deps = []

foreach p : subprojects 
    required_deps += dependency(p, fallback : [p, 'this_dep'])
endforeach

directories = ['source']

directories = include_directories(directories)

this_lib = library(meson.project_name(),
    sources,
    include_directories: directories,
    install: true,
    version: meson.project_version(),
    dependencies: required_deps,
)

this_dep = declare_dependency(
    link_with: [this_lib],
    include_directories: directories,
    dependencies: required_deps,
)

test_versions = ['mir_stat_test']

install_subdir('source/',
    strip_directory : true,
    install_dir: 'include/d/' + meson.project_name(),
)

import('pkgconfig').generate(this_lib,
    description: description,
    subdirs: 'd/' + meson.project_name(),
)

mir_stat_dep = this_dep
mir_stat_lib = this_lib
```

**Comment by 9il** [comment]
> @9il I started looking at the `meson.build` file in `mir-algorithm` and have adapted it to below. I wasn't sure how exactly to handle the dependency on mir-algorithm here. You use a subproject for mir-core in that one. Do the same here (but for mir-algorithm)? If not, then what to put?

needs both and `subprojects = ['mir-core', 'mir-algorithm']`

**Comment by jmh530** [comment]
Reminder that azure-pipelines should be added instead of appveyor. See [#8](https://github.com/libmir/mir-stat/pull/8).

**Comment by jmh530** [comment]
Travis no longer required because github actions replaced it. See PRs [#25](https://github.com/libmir/mir-stat/pull/25) and [#26](https://github.com/libmir/mir-stat/pull/26)

**Comment by jmh530** [comment]
@9il It looks like Circle CI is still running (see [here](https://app.circleci.com/pipelines/github/libmir/mir-stat)), but I don't see the results of it with the other CI being run. Any idea why that is?

**Comment by jmh530** [comment]
@9il Hmm, it seems that the Circle CI only runs on merge, rather than for every PR.

**Comment by 9il** [comment]
Probably it is limited to MRs from libmir (because of AWS keys), do you have permission to push new branches ?

**Comment by jmh530** [comment]
It looks like I have permission to add new branches: 

https://github.com/libmir/mir-stat/tree/test

**Comment by jmh530** [comment]
@9il It looks like there was an option to build forked PRs that was unchecked. It looks like checking that resolved it (created a test PR to check). I think this can get closed now.
