### ISSUE TITLE
Q (feature request): RobustScaler

### ISSUE THREAD

**Issue by mw66** [libmir/mir-stat#20]
https://github.com/libmir/mir-algorithm/issues/322

jmh530:
"""
@mingwugmail As @9il indicates, you should be able to use transform with median and interquartileRange to get the basic functionality, although it may not be the most efficient approach. It would be more efficient to calculate the median and the interquartile range at the same time, which would require new functionality.
"""

**Comment by jmh530** [comment]
@mingwugmail Just added `robustScale` function.

**Comment by mw66** [comment]
@jmh530 Thank you!

**Comment by jmh530** [comment]
@mingwugmail Still need to tag a new release. I have some fixes to add later tonight first.

**Comment by mw66** [comment]
@jmh530 No problem, I'm patient.

**Comment by jmh530** [comment]
@mingwugmail New tag available.

**Comment by mw66** [comment]
@jmh530  you are my hero!
